config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, 
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      registration: 'signup'
    },
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
    }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :species
  resources :plants
  root to: "species#index"
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.superadmin_role?
      can :manage, :all
      can :access, :rails_admin
      can :manage, Plant
      can :manage, Species
    end
    
    if user.supervisor_role?
      can :manage, User
      can :create, Plant
      can :update, Plant
      can :read, Plant
      
      can :create, Species
      can :update, Species
      can :read, Species
    end

    if user.user_role? 
      can :read, Plant
      can :read, Species
    end

    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dimension.rb
class Dimension < ApplicationRecord
end

app/models/flower.rb
class Flower < ApplicationRecord
    belongs_to :species
end

app/models/foliage.rb
class Foliage < ApplicationRecord
    belongs_to :species
end

app/models/fruit_or_seed.rb
class FruitOrSeed < ApplicationRecord
end

app/models/growth.rb
class Growth < ApplicationRecord
    belongs_to :species
    # has_one :temperature_minimum, class_name: 'Temperature', dependant: :destroy
    # has_one :temperature_maximum, class_name: 'Temperature', dependant: :destroy
end

app/models/image.rb
class Image < ApplicationRecord
    belongs_to :imageable, polymorphic: true
end

app/models/jwt_blacklist.rb
class JwtBlacklist < ApplicationRecord
    include Devise::JWT::RevocationStrategies::Blacklist

    self.table_name = 'jwt_blacklist'
end

app/models/plant.rb
class Plant < ApplicationRecord    
    has_rich_text :description

    belongs_to :species

    has_many :plant_images
    
    accepts_nested_attributes_for :plant_images, allow_destroy: true, reject_if: lambda { |attributes| 
        exists = attributes[:id].present?
        empty = attributes[:url].blank?
        attributes.merge!({_destroy: 1}) if exists and empty
        
        return (!exists and empty)
    }

    validates :scientific_name, presence: true
end

app/models/plant_image.rb
class PlantImage < ApplicationRecord
    belongs_to :plant
end

app/models/propagation.rb
class Propagation < ApplicationRecord
    belongs_to :species
end

app/models/seed.rb
class Seed < ApplicationRecord
end

app/models/species.rb
class Species < ApplicationRecord
    include Imageable
    
    has_rich_text :description
    
    has_many :plants
    has_many :species_images

    has_one :flower, dependent: :destroy
    has_one :foliage, dependent: :destroy
    has_one :propagation, dependent: :destroy
    has_one :growth, dependent: :destroy

    accepts_nested_attributes_for :flower, allow_destroy: true
    accepts_nested_attributes_for :foliage, allow_destroy: true
    accepts_nested_attributes_for :propagation, allow_destroy: true
    accepts_nested_attributes_for :growth, allow_destroy: true
    accepts_nested_attributes_for :species_images, allow_destroy: true, reject_if: lambda { |attributes|
        exists = attributes[:id].present?
        empty = attributes[:url].blank?
        attributes.merge!({_destroy: 1}) if exists and empty
        return (!exists and empty)
    }

    validates :scientific_name, presence: true
end

app/models/species_image.rb
class SpeciesImage < ApplicationRecord
    belongs_to :species
end

app/models/specification.rb
class Specification < ApplicationRecord
end

app/models/temperature.rb
class Temperature < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :jwt_authenticatable, jwt_revocation_strategy: JwtBlacklist
end

app/controllers/species_controller.rb
class SpeciesController < ApplicationController
  before_action :set_species, only: [:show, :edit, :update, :destroy]

  # GET /species
  # GET /species.json
  def index
    @species = Species.paginate(page: params[:page], per_page: 10).order('scientific_name ASC')
  end

  # GET /species/1
  # GET /species/1.json
  def show
  end

  # GET /species/new
  def new
    @species = Species.new
    @species.flower = Flower.new
    @species.foliage = Foliage.new
    @species.propagation = Propagation.new
    @species.growth = Growth.new
    @species.species_images.build
  end

  # GET /species/1/edit
  def edit
    @species.species_images.build
  end

  # POST /species
  # POST /species.json
  def create
    @species = Species.new(species_params)

    respond_to do |format|
      if @species.save
        format.html { redirect_to @species, notice: 'Species was successfully created.' }
        format.json { render :show, status: :created, location: @species }
      else
        format.html { render :new }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /species/1
  # PATCH/PUT /species/1.json
  def update
    respond_to do |format|
      if @species.update(species_params)
        format.html { redirect_to edit_species_path(@species), notice: 'Species was successfully updated.' }
        format.json { render :show, status: :ok, location: @species }
      else
        format.html { render :edit }
        format.json { render json: @species.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /species/1
  # DELETE /species/1.json
  def destroy
    @species.destroy
    respond_to do |format|
      format.html { redirect_to species_index_url, notice: 'Species was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_species
      @species = Species.find(params[:id])
      
      @species.flower = Flower.new unless @species.flower.present?
      @species.foliage = Foliage.new unless @species.foliage.present?
      @species.propagation = Propagation.new unless @species.propagation.present?
      @species.growth = Growth.new unless @species.growth.present?
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def species_params
      params.require(:species).permit(
        :id, 
        :duration, 
        :common_name, 
        :year, 
        :type, 
        :scientific_name, 
        :native_status,
        :description,
        flower_attributes: [:id, '_destroy', :conspicuous, :color],
        foliage_attributes: [:id, '_destroy', :texture, :porosity_winter, :porosity_summer, :color],
        propagation_attributes: [:id, '_destroy', :tubers, :sprigs, :sod, :seed, :cuttings, :corms, :container, :bulbs, :bare_root],
        growth_attributes: [:id, '_destroy', :shade_tolerance, :salinity_tolerance, :ph_minimum, :ph_maximum, :moisture_use],
        species_images_attributes: [:id, :url, '_destroy'],
      )
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/helpers/species_helper.rb
module SpeciesHelper
end

app/views/species/_form.html.erb
<%= form_with(model: species, local: true) do |form| %>
  <% if species.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(species.errors.count, "error") %> prohibited this species from being saved:</h2>

      <ul>
        <% species.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label t(:scientific_name) %>
    <%= form.text_field :scientific_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label t(:common_name) %>
    <%= form.text_field :common_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label t(:native_status) %>
    <%= form.text_field :native_status, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label t(:description) %>
    <%= form.rich_text_area :description %>
  </div>

  <div class="card mt-4">
    <div class="card-body">
      <div class="card-title">
        <h5><%= t :image_links%></h5>
      </div>
  
      <%= form.fields_for :species_images do |ff|%>
        <div class="form-group">
          <%= ff.label t(:url) %>
          <%= ff.text_field :url, class: "form-control"%>
          
          <%= ff.check_box :_destroy %>
          <%= ff.label :_destroy, t(:destroy)  %>
        </div>
      <% end %>
    </div>
  </div>

  <div id="accordion">
    <div class="card mt-4">
      <div class="card-header">
        <h5 class="mb-0">
          <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#collapseOne">
            <%= t :flower%>
          </button>
        </h5>
      </div>

      <div id="collapseOne" class="collapse" data-parent="#accordion">
        <div class="card-body">
          <%= form.fields_for :flower do |ff|%>
            <div class="form-group">
              <%= ff.label  t(:conspicuous) %>
              <%= ff.select :conspicuous , [[t(:visible), 'conspicuous'], [t(:not_visible), 'inconspicuous']], {}, { class: "form-control" }%>
            </div>

            <div class="form-group">  
              <%= ff.label t(:color) %>
              <%= ff.text_field :color, class: "form-control"%>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="card mt-4">
      <div class="card-header">
        <h5 class="mb-0">
          <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#collapse-2">
            <%= t(:foliage) %>
          </button>
        </h5>
      </div>

      <div id="collapse-2" class="collapse" data-parent="#accordion">
        <div class="card-body">
          <%= form.fields_for :foliage do |ff|%>
            <div class="form-group">  
              <%= ff.label t(:texture) %>
              <%= ff.text_field :texture, class: "form-control"%>
            </div>

            <div class="form-group">  
              <%= ff.label t(:porosity_winter) %>
              <%= ff.text_field :porosity_winter, class: "form-control"%>
            </div>

            <div class="form-group">  
              <%= ff.label t(:porosity_summer) %>
              <%= ff.text_field :porosity_summer, class: "form-control"%>
            </div>

            <div class="form-group">  
              <%= ff.label t(:color) %>
              <%= ff.text_field :color, class: "form-control"%>
            </div>
          <% end %>
        </div>
      </div>
    </div>

    <div class="card mt-4">
      <div class="card-header">
        <h5 class="mb-0">
          <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#collapse-3">
            <%= t :propagation %>
          </button>
        </h5>
      </div>

      <div id="collapse-3" class="collapse" data-parent="#accordion">
        <div class="card-body">
          <%= form.fields_for :propagation do |ff|%>
            <div class="form-group">  
              <%= ff.label t(:tubers) %>
              <%= ff.text_field :tubers, class: "form-control"%>
            </div>

            <div class="form-group">  
              <%= ff.label t(:sprigs) %>
              <%= ff.text_field :sprigs, class: "form-control"%>
            </div>

            <div class="form-group">  
              <%= ff.label t(:sod) %>
              <%= ff.text_field :sod, class: "form-control"%>
            </div>

            <div class="form-group">  
              <%= ff.label t(:seed) %>
              <%= ff.text_field :seed, class: "form-control"%>
            </div>

            <div class="form-group">  
              <%= ff.label t(:cuttings) %>
              <%= ff.text_field :cuttings, class: "form-control"%>
            </div>

            <div class="form-group">  
              <%= ff.label t(:corms) %>
              <%= ff.text_field :corms, class: "form-control"%>
            </div>

            <div class="form-group">  
              <%= ff.label t(:container) %>
              <%= ff.text_field :container, class: "form-control"%>
            </div>

            <div class="form-group">  
              <%= ff.label t(:bulbs) %>
              <%= ff.text_field :bulbs, class: "form-control"%>
            </div>
            
            <div class="form-group">  
              <%= ff.label t(:bare_root) %>
              <%= ff.text_field :bare_root, class: "form-control"%>
            </div>
          <% end %>
        </div>
      </div>
    </div>

        <div class="card mt-4">
      <div class="card-header">
        <h5 class="mb-0">
          <button type="button" class="btn btn-link" data-toggle="collapse" data-target="#collapse-4">
            <%= t :growth %>
          </button>
        </h5>
      </div>

      <div id="collapse-4" class="collapse" data-parent="#accordion">
        <div class="card-body">
          <%= form.fields_for :growth do |ff|%>
            <div class="form-group">  
              <%= ff.label t(:shade_tolerance) %>
              <%= ff.text_field :shade_tolerance, class: "form-control"%>
            </div>

            <div class="form-group">  
              <%= ff.label t(:salinity_tolerance) %>
              <%= ff.text_field :salinity_tolerance, class: "form-control"%>
            </div>

            <div class="form-group">  
              <%= ff.label t(:ph_minimum) %>
              <%= ff.text_field :ph_minimum, class: "form-control"%>
            </div>

            <div class="form-group">  
              <%= ff.label t(:ph_maximum) %>
              <%= ff.text_field :ph_maximum, class: "form-control"%>
            </div>

            <div class="form-group">  
              <%= ff.label t(:moisture_use) %>
              <%= ff.text_field :moisture_use, class: "form-control"%>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

  <%= form.submit t(:save), class: 'btn btn-primary mt-3'%>
<% end %>

app/views/species/edit.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title text-capitalize">
      <%= t :edit %>
    </h5>
  </div>
</div>

<div class="card mt-3 mb-3">
  <div class="card-body" style="padding: 0.25rem;">
    <%= link_to t(:back), species_index_path, class:'btn btn-link', role: 'button' %>
    <%= link_to t(:show), @species, class:'btn btn-link', role: 'button' %>
  </div>
</div>

<%= render 'form', species: @species %>

app/views/species/index.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title">
      <%= t :species %>
    </h5>
  </div>
</div>

<div class="card mt-3 mb-3">
  <div class="card-body" style="padding: 0.25rem;">
    <%= link_to t(:new_species), new_species_path, class: 'btn btn-link' %>
  </div>
</div>

<div class="card">
  <div class="card-body">
    <table class="table table-bordered table-responsive-sm table-responsive-md">
      <thead>
        <tr class="text-center">
          <th scope="col">id</th>
          <th scope="col"><%= t :scientific_name %></th>
          <th scope="col"><%= t :common_name%></th>
          <th scope="col"><%= t :native_status%></th>
          <th scope="col"colspan="3"><%= t :actions %></th>
        </tr>
      </thead>

      <tbody>
        <% @species.each do |species| %>
          <tr>
            <td scope="row" class="text-center"><%= species.id %></td>
            <td><%= link_to species.scientific_name, species_path(species) %></td>
            <td><%= species.common_name %></td>
            <td><%= species.native_status %></td>
              <% if can? :read, Species %>
                <td class="text-center">
                  <%= link_to species do %>
                    <i class="fas fa-eye"></i>
                  <% end %>
                </td>
              <% end %>
              <% if can? :update, Species %>
                <td class="text-center">
                  <%= link_to edit_species_path(species) do %>
                    <i class="fas fa-pencil-alt"></i>
                  <% end %>
                </td>
              <% end %>

              <% if can? :destroy, Species %>
                <td class="text-center">
                  <%= link_to species, method: :delete, data: { confirm: t(:confirm_delete) } do %>
                    <i class="fas fa-trash-alt"></i>
                  <% end %>
                </td>
              <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= will_paginate @plants, list_classes: %w(pagination justify-content-center), renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

app/views/species/new.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title text-capitalize">
      <%= t :new_species %>
    </h5>
  </div>
</div>

<div class="card mt-3 mb-3">
  <div class="card-body" style="padding: 0.25rem;">
    <%= link_to t(:back), species_index_path, class: 'btn btn-link' %>
  </div>
</div>

<%= render 'form', species: @species %>

app/views/species/show.html.erb
<div class="card mt-3 mb-3">
  <div class="card-body" style="padding: 0.25rem;">
    <%= link_to t(:back), species_index_path, class: 'btn btn-link'%>
    <%= link_to t(:edit), edit_species_path(@species), class: 'btn btn-link'%>
  </div>
</div>

<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title"><%= @species.scientific_name %></h5>
    <h6 class="card-subtitle text-muted"><%= @species.common_name %></h6>
  </div>
</div>

<table class="table table-bordered table-responsive-sm table-responsive-md">
  <tbody>
    <tr>
      <td class="font-weight-bold" scope="col">id</td>
      <td scope="col"><%= @species.id %></td>
    </tr>
    
    <tr>
      <td class="font-weight-bold" scope="col">
        <%= t :scientific_name %>
      </td>
      <td scope="col"><%= @species.scientific_name %></td>
    </tr>
    
    <tr>
      <td class="font-weight-bold" scope="col">
        <%= t :common_name %>
      </td>
      <td scope="col"><%= @species.common_name %></td>
    </tr>
    
    <tr>
      <td class="font-weight-bold" scope="col">
        <%= t :native_status%>
      </td>
      <td scope="col"><%= @species.native_status %></td>
    </tr>
  </tbody>
</table>

<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title">
        <%= t :description%>
    </h5>
    <%= @species.description %>
  </div>
</div>

<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title">
        <%= t :images%>
    </h5>
    
    <ul class="list-group list-group-flush">
      <% @species.species_images.each do |image| %>
        <li class="list-group-item">
          <%= link_to image.url %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title">
        <%= t :flower%>
    </h5>
  
    <table class="table table-bordered table-responsive-sm table-responsive-md">
      <tbody>
        <tr>
          <td class="font-weight-bold" scope="col">
            <%= t :conspicuous%>
          </td>
          <td scope="col"><%= @species.flower.conspicuous %></td>
        </tr>
        
        <tr>
          <td class="font-weight-bold" scope="col">
            <%= t :color%>
          </td>
          <td scope="col"><%= @species.flower.color %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title">
        <%= t :foliage%>
    </h5>

    <table class="table table-bordered table-responsive-sm table-responsive-md">
      <tbody>
        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :texture%>
          </td>
          <td scope="col"><%= @species.foliage.texture %></td>
        </tr>
        
        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :porosity_winter%>
          </td>
          <td scope="col"><%= @species.foliage.porosity_winter %></td>
        </tr>

        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :porosity_winter%>
          </td>
          <td scope="col"><%= @species.foliage.porosity_summer %></td>
        </tr>

        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :color%>
          </td>
          <td scope="col"><%= @species.foliage.color %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title">
      <%= t :propagation%>
    </h5>
  
    <table class="table table-bordered table-responsive-sm table-responsive-md">
      <tbody>
        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :tubers %>
          </td>
          <td scope="col"><%= @species.propagation.tubers %></td>
        </tr>
        
        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :sprigs %>
          </td>
          <td scope="col"><%= @species.propagation.sprigs %></td>
        </tr>

        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :sod %>
          </td>
          <td scope="col"><%= @species.propagation.sod %></td>
        </tr>

        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :seed %>
          </td>
          <td scope="col"><%= @species.propagation.seed %></td>
        </tr>

        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :cuttings %>
          </td>
          <td scope="col"><%= @species.propagation.cuttings %></td>
        </tr>
        
        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :corms %>
          </td>
          <td scope="col"><%= @species.propagation.corms %></td>
        </tr>

        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :container %>
          </td>
          <td scope="col"><%= @species.propagation.container %></td>
        </tr>

        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :bulbs %>
          </td>
          <td scope="col"><%= @species.propagation.bulbs %></td>
        </tr>
        
        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :bare_root %>
          </td>
          <td scope="col"><%= @species.propagation.bare_root %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>

<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title">
        <%= t :growth%>
    </h5>
  
    <table class="table table-bordered table-responsive-sm table-responsive-md">
      <tbody>
        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :shade_tollerance %>
          </td>
          <td scope="col"><%= @species.growth.shade_tolerance %></td>
        </tr>
        
        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :salinity_tollerance %>
          </td>
          <td scope="col"><%= @species.growth.salinity_tolerance %></td>
        </tr>

        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :ph_minimum %>
          </td>
          <td scope="col"><%= @species.growth.ph_minimum %></td>
        </tr>

        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :ph_maximum %>
          </td>
          <td scope="col"><%= @species.growth.ph_maximum %></td>
        </tr>

        <tr>
          <td class="font-weight-bold" scope="col-3">
            <%= t :moisture_use %>
          </td>
          <td scope="col"><%= @species.growth.moisture_use %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>