config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  
  devise_for :users, 
    path_names: {
      sign_in: 'login',
      sign_out: 'logout',
      registration: 'signup'
    },
    controllers: {
      sessions: 'users/sessions',
      registrations: 'users/registrations',
      passwords: 'users/passwords',
    }

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
  end
  
  resources :species
  resources :plants
  root to: "species#index"
end

app/models/plant.rb
class Plant < ApplicationRecord    
    has_rich_text :description

    belongs_to :species

    has_many :plant_images
    
    accepts_nested_attributes_for :plant_images, allow_destroy: true, reject_if: lambda { |attributes| 
        exists = attributes[:id].present?
        empty = attributes[:url].blank?
        attributes.merge!({_destroy: 1}) if exists and empty
        
        return (!exists and empty)
    }

    validates :scientific_name, presence: true
end

app/controllers/plants_controller.rb
class PlantsController < ApplicationController
  before_action :set_plant, only: [:show, :edit, :update, :destroy]
  before_action :set_species, only: [:new, :create, :show, :edit, :update]
  load_and_authorize_resource

  # GET /plants
  # GET /plants.json
  def index
    @plants = Plant.paginate(page: params[:page], per_page: 10).order('id ASC')
  end
  
  # GET /plants/1
  # GET /plants/1.json
  def show
  end
  
  # GET /plants/new
  def new
    @plant = Plant.new
    @plant.plant_images.build

    @species = Species.all
  end

  # GET /plants/1/edit
  def edit
    @plant.plant_images.build
  end

  # POST /plants
  # POST /plants.json
  def create
    @plant = Plant.new(plant_params)

    respond_to do |format|
      if @plant.save
        format.html { redirect_to @plant, notice: 'Plant was successfully created.' }
        format.json { render :show, status: :created, location: @plant }
      else
        format.html { render :new }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plants/1
  # PATCH/PUT /plants/1.json
  def update
    respond_to do |format|
      if @plant.update(plant_params)
        format.html { redirect_to edit_plant_path(@plant), notice: 'Plant was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant }
      else
        format.html { render :edit }
        format.json { render json: @plant.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plants/1
  # DELETE /plants/1.json
  def destroy
    @plant.destroy
    respond_to do |format|
      format.html { redirect_to plants_url, notice: 'Plant was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant
      @plant = Plant.find(params[:id])
    end

    def set_species
      @species = Species.all
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_params
      params.require(:plant).permit(
          :id, 
          :description,
          :scientific_name,
          :common_name, 
          :native_status,
          :species_id,
          plant_images_attributes: [:id, :url, '_destroy']
        )
    end
end

app/helpers/plants_helper.rb
module PlantsHelper
end

app/views/plants/_form.html.erb
<%= form_with(model: plant, local: true) do |form| %>
  <% if plant.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plant.errors.count, "error") %> prohibited this plant from being saved:</h2>

      <ul>
        <% plant.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label t(:scientific_name) %>
    <%= form.text_field :scientific_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label t(:common_name) %>
    <%= form.text_field :common_name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label t(:native_status) %>
    <%= form.text_field :native_status, class: "form-control" %>
  </div>

  <div class ="form-group">
    <%= form.label t(:species) %>
    <%= form.select :species_id , @species.collect {|s| [s.scientific_name, s.id]}, {}, { class: "form-control" }%>
  </div>

  <div class="form-group">
    <%= form.label t(:description) %>
    <%= form.rich_text_area :description %>
  </div>

  <div class="card mt-4">
    <div class="card-body">
      <div class="card-title">
        <h5><%= t :image_links%></h5>
      </div>

      <%= form.fields_for :plant_images do |ff|%>
        <div class="form-group">
          <%= ff.label t(:url) %>
          <%= ff.text_field :url, class: "form-control"%>
          
          <%= ff.check_box :_destroy %>
          <%= ff.label :_destroy, t(:destroy) %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="mt-3">
    <%= form.submit t(:save), class: "btn btn-primary" %>
  </div>
<% end %>

app/views/plants/_nav_bar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">PlantPedia</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Alterna navegação">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <li class="nav-item <%= 'active' if current_page?(plants_path) %>">
        <a class="nav-link" href="/plants">
          <%= t :plants%>
        </a>
      </li>
      <li class="nav-item <%= 'active' if current_page?(species_index_path) %>">
        <a class="nav-link" href="/species">
          <%= t :species%>
        </a>
      </li>
    </ul>

    <form class="form-inline my-2 my-lg-0">
      <% if current_user.present? %>
        <span class="navbar-text mr-3"><%= t :welcome%>, <%= current_user.email%></span>
        <%= link_to t(:logout), destroy_user_session_path, method: :delete%>
      <%end%>
    </form>
  </div>
</nav>

app/views/plants/edit.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title text-capitalize">
      <%= t :edit %>
    </h5>
  </div>
</div>

<div class="card mt-3 mb-3">
  <div class="card-body" style="padding: 0.25rem;">
    <%= link_to t(:back), plants_path, class: 'btn btn-link'%>
    <%= link_to t(:show), @plant, class: 'btn btn-link'%>
  </div>
</div>

<%= render 'form', plant: @plant %>

app/views/plants/index.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title">
      <%= t :plants %>
    </h5>
  </div>
</div>

<div class="card mt-3 mb-3">
  <div class="card-body" style="padding: 0.25rem;">
    <%= link_to t(:new_plant), new_plant_path, class: 'btn btn-link' %>
  </div>
</div>

<div class="card">
    <div class="card-body">
      <table class="table table-bordered table-responsive-sm table-responsive-md">
        <thead>
          <tr class="text-center">
            <th scope="col">id</th>
            <th scope="col">
              <%= t :scientific_name%>
            </th>
            <th scope="col">
              <%= t :common_name%>
            </th>
            <th scope="col">
              <%= t :native_status%>
            </th>
            <th scope="col"colspan="3">
              <%= t :actions%>
            </th>
          </tr>
        </thead>

        <tbody>
          <% @plants.each do |plant| %>
            <tr>
              <td scope="row" class="text-center"><%= plant.id %></td>
              <td><%= link_to plant.scientific_name, plant_path(plant) %></td>
              <td><%= plant.common_name %></td>
              <td><%= plant.native_status %></td>
                <td class="text-center">
                  <%= link_to plant do %>
                    <i class="fas fa-eye"></i>
                  <% end %>
                </td>
                
                <% if can? :update, Plant %>
                  <td class="text-center">
                    <%= link_to edit_plant_path(plant) do %>
                      <i class="fas fa-pencil-alt"></i>
                    <% end %>
                  </td>
                <% end %>

                <% if can? :destroy, Plant %>
                  <td class="text-center">
                    <%= link_to plant, method: :delete, data: { confirm: t(:confirm_delete) } do %>
                      <i class="fas fa-trash-alt"></i>
                    <% end %>
                  </td>
                <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= will_paginate @plants, list_classes: %w(pagination justify-content-center), renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
    </div>
</div>

app/views/plants/new.html.erb
<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title text-capitalize">
      <%= t :new_plant %>
    </h5>
  </div>
</div>

<div class="card mt-3 mb-3">
  <div class="card-body" style="padding: 0.25rem;">
    <%= link_to t(:back), plants_path, class: 'btn btn-link' %>
  </div>
</div>

<%= render 'form', plant: @plant%>

app/views/plants/show.html.erb
<div class="card mt-3 mb-3">
  <div class="card-body" style="padding: 0.25rem;">
    <%= link_to t(:back), plants_path, class: 'btn btn-link' %>
    <%= link_to t(:edit), edit_plant_path(@plant), class: 'btn btn-link' %>
  </div>
</div>

<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title"><%= @plant.scientific_name %></h5>
    <h6 class="card-subtitle text-muted"><%= @plant.common_name %></h6>
  </div>
</div>

<table class="table table-bordered table-responsive-sm table-responsive-md">
  <tbody>
    <tr>
      <td class="font-weight-bold" scope="col">id</td>
      <td scope="col"><%= @plant.id %></td>
    </tr>
    
    <tr>
      <td class="font-weight-bold" scope="col">
        <%= t :scientific_name %>
      </td>
      <td scope="col"><%= @plant.scientific_name %></td>
    </tr>
    
    <tr>
      <td class="font-weight-bold" scope="col">
        <%= t :common_name %>
      </td>
      <td scope="col"><%= @plant.common_name %></td>
    </tr>
    
    <tr>
      <td class="font-weight-bold" scope="col">
        <%= t :native_status %>
      </td>
      <td scope="col"><%= @plant.native_status %></td>
    </tr>
  </tbody>
</table>

<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title">
      <%= t :description %>
    </h5>
    <%= @plant.description %>
  </div>
</div>

<div class="card mb-4">
  <div class="card-body">
    <h5 class="card-title">
      <%= t :image_links%>
    </h5>
  </div>

  <ul class="list-group list-group-flush">
    <% @plant.plant_images.each do |image| %>
      <li class="list-group-item">
        <%= link_to image.url %>
      </li>
    <% end %>
  </ul>
</div>